[build]
  publish = "." # root folder (your index.html is here)

[context.production.environment]
  NODE_VERSION = "18" # explicitly tell Netlify to use Node 18

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "@netlify/plugin-sitemap"
