[build.environment]
  NODE_VERSION = "18.19.0"  # Specific version
  NPM_FLAGS = "--production"

[build]
  publish = "."
  command = "npm run build"

# Clean redirect configuration
[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/roms"
  to = "/rom"
  status = 200

[[redirects]]
  from = "/downloads"
  to = "/download"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Only enable plugins that are essential and compatible
[[plugins]]
  package = "@netlify/plugin-sitemap"
