[build.environment]
  NODE_VERSION = "18.19.1"
  # Disable plugin loading
  NETLIFY_EXPERIMENTAL_BUILD_PLUGINS_API = "false"
  # Skip problematic plugins
  NETLIFY_SKIP_PLUGINS = "@netlify/plugin-lighthouse,netlify-plugin-submit-sitemap,@netlify/plugin-sitemap"

[build]
  publish = "."
  command = "npm run build"

# EXPLICITLY override any plugins with empty list
plugins = []

# Redirects only
[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/roms"
  to = "/rom"
  status = 200

[[redirects]]
  from = "/downloads"
  to = "/download"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
