[build]
  publish = "dist" # or your output folder
  node_version = "18"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "@netlify/plugin-sitemap"
