[build]
  publish = "."

[context.production.environment]
  NODE_VERSION = "18"

# Disable Lighthouse in production for faster deploys
[context.deploy-preview]
  [[plugins]]
    package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "@netlify/plugin-sitemap"
